"""Chart and figure detection with CLIP + Bedrock Nova vision captioning.

HOW IT WORKS (simple analogy):
  Imagine you have a stack of screenshots from a financial report.
  You want to know: "Is this image a chart/graph, or just a logo/photo?"

  Step 1 — CLIP (local AI, very fast):
    CLIP looks at each image and scores it against descriptions like
    "a bar chart", "a pie chart", "a photograph", etc.
    If the combined score for chart-like descriptions is above the threshold,
    we classify it as a chart. No internet needed — runs on your machine.

  Step 2 — Bedrock Nova Vision (AWS AI, slower):
    For images that passed the CLIP filter, we send them to Amazon Nova Lite
    and ask: "Describe this financial chart in detail."
    This gives us a rich text caption — what the chart shows, its axes, trends.

  Step 3 — ChartNode:
    We wrap the image bytes + caption into a ChartNode object.
    The RAG pipeline later adds this caption as a searchable text chunk,
    so users can ask questions about charts (e.g. "What was revenue in 2023?")

Pipeline:
1. CLIP zero-shot classification to score whether an image is a chart/graph.
2. If score exceeds the threshold, send the image to Bedrock Nova for a
   detailed financial-chart caption.
3. Return a ChartNode with image bytes and the generated caption.
"""

from __future__ import annotations

import base64
import io
import json
import logging
from dataclasses import dataclass
from typing import Optional

import boto3
import open_clip   # OpenCLIP — local vision-language model for image classification
import torch
from PIL import Image

logger = logging.getLogger(__name__)

# ── CLIP Label Definitions ────────────────────────────────────────────────────
# These are the text descriptions we compare each image against.
# CLIP will score how well each image matches each description.
# Think of these as the "categories" in a classification workflow.
_CHART_LABELS = [
    "a financial chart or graph",
    "a table of numbers or data",
    "a bar chart",
    "a line graph",
    "a pie chart",
    "a scatter plot",
    "a candlestick chart",
    "a heat map",
    "an infographic",
    "a photograph",         # negative — not a chart
    "a logo or icon",       # negative — not a chart
    "decorative artwork",   # negative — not a chart
    "a text paragraph",     # negative — not a chart
]

# The "positive" labels — if the combined probability of these labels
# exceeds the threshold, we call it a chart
_CHART_POSITIVE_LABELS = {
    "a financial chart or graph",
    "a table of numbers or data",
    "a bar chart",
    "a line graph",
    "a pie chart",
    "a scatter plot",
    "a candlestick chart",
    "a heat map",
    "an infographic",
}


@dataclass
class ChartNode:
    """Represents a detected chart/figure with its auto-generated caption.

    After processing, this holds everything we know about one chart image:
    - The image itself (as PNG bytes)
    - A text caption generated by Bedrock Nova describing what the chart shows
    - Metadata: which page it came from, what type of chart CLIP thinks it is
    """

    image_bytes: bytes      # raw PNG bytes of the chart image
    caption: str            # AI-generated description of the chart (from Bedrock)
    chart_type: str         # top CLIP label (e.g. "a bar chart")
    clip_score: float       # CLIP confidence score — how "chart-like" is this image?
    page_number: int        # which page of the PDF this came from (0-indexed)
    image_index: int        # position within that page's image list
    source: str             # filename or S3 key of the source PDF
    width: int              # image width in pixels
    height: int             # image height in pixels

    def to_dict(self) -> dict:
        """Serialise to a plain dict for JSON responses and storage."""
        return {
            "caption": self.caption,
            "chart_type": self.chart_type,
            "clip_score": self.clip_score,
            "page_number": self.page_number,
            "image_index": self.image_index,
            "source": self.source,
            "width": self.width,
            "height": self.height,
            # Encode image as base64 string so it can be included in JSON responses
            "image_b64": base64.b64encode(self.image_bytes).decode(),
        }


class ChartExtractor:
    """Detect charts and generate captions using CLIP + Bedrock Nova vision.

    Parameters
    ----------
    clip_model_name:
        Open CLIP model name (e.g. ``"ViT-B-32"``).
        ViT-B-32 is a good balance of speed and accuracy.
    clip_pretrained:
        Open CLIP pretrained weights tag (e.g. ``"openai"``).
    chart_threshold:
        Minimum combined CLIP probability for positive chart labels to classify
        an image as a chart. 0.45 = 45% confidence required.
    bedrock_model_id:
        Bedrock model to use for vision captioning (Nova Lite by default).
    aws_region:
        AWS region for the Bedrock client.
    device:
        PyTorch device string; defaults to CUDA if available, else CPU.
    """

    def __init__(
        self,
        clip_model_name: str = "ViT-B-32",
        clip_pretrained: str = "openai",
        chart_threshold: float = 0.45,
        bedrock_model_id: str = "amazon.nova-lite-v1:0",
        aws_region: str = "us-east-1",
        device: Optional[str] = None,
        session_kwargs: Optional[dict] = None,
    ) -> None:
        self.chart_threshold = chart_threshold
        self.bedrock_model_id = bedrock_model_id
        # Use GPU (cuda) if available, otherwise CPU
        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")

        # Load the CLIP model — this stays in memory for all images in the session
        logger.info("Loading CLIP model %s/%s on %s", clip_model_name, clip_pretrained, self.device)
        self._model, _, self._preprocess = open_clip.create_model_and_transforms(
            clip_model_name, pretrained=clip_pretrained
        )
        self._model = self._model.to(self.device).eval()  # move to device and set to eval mode
        self._tokenizer = open_clip.get_tokenizer(clip_model_name)

        # Pre-compute text features for all chart labels ONCE at startup
        # (No need to re-compute on every image — the labels never change)
        self._text_features = self._encode_labels()

        # Create a Bedrock client for vision captioning
        session = boto3.Session(**(session_kwargs or {}))
        self._bedrock = session.client("bedrock-runtime", region_name=aws_region)

    # ── Public API ────────────────────────────────────────────────────────────

    def is_chart(self, image: Image.Image) -> tuple[bool, float, str]:
        """Decide if an image is a chart/graph using CLIP zero-shot classification.

        Returns a tuple of:
        - is_chart (bool): True if the combined chart-label probability >= threshold
        - chart_probability (float): summed probability for all positive chart labels
        - top_label (str): the single highest-scoring label name

        Example:
          is_chart, score, label = extractor.is_chart(my_image)
          # → (True, 0.72, "a bar chart")
        """
        probs, top_label = self._clip_classify(image)
        # Sum the probabilities for all "positive" chart label categories
        chart_prob = sum(
            p for label, p in zip(_CHART_LABELS, probs.tolist())
            if label in _CHART_POSITIVE_LABELS
        )
        return chart_prob >= self.chart_threshold, chart_prob, top_label

    def caption_chart(self, image: Image.Image, source_context: str = "") -> str:
        """Generate a detailed financial caption for a chart image via Bedrock Nova.

        Sends the image + a carefully crafted prompt to Bedrock.
        The prompt tells the model to act as a financial analyst and describe:
          - chart type
          - axes and units
          - key trends and data points
          - notable anomalies

        Handles two different API formats:
          - Nova format: {"text": "..."} for text, {"image": {...}} for images
          - Claude format: {"type": "text", "text": "..."} for text

        Returns the caption string, or a fallback message if captioning fails.
        """
        img_b64 = _image_to_base64(image)

        # Build the analyst prompt — detailed instructions for the AI
        prompt_text = (
            "You are a financial analyst examining a chart or figure from a financial document. "
            "Provide a detailed, precise description of this chart including: "
            "(1) the chart type, (2) the title or subject matter if visible, "
            "(3) the axes labels and units, (4) key data trends or insights, "
            "(5) any notable data points, peaks, troughs, or anomalies. "
            "Be specific about numerical values where legible. "
        )
        if source_context:
            prompt_text += f"Context: this image comes from '{source_context}'. "
        prompt_text += "Description:"

        # Check which model format to use — Nova vs Claude have different API schemas
        is_nova = "nova" in self.bedrock_model_id.lower()
        if is_nova:
            # Nova format: image block uses {"image": {"format": ..., "source": {"bytes": ...}}}
            body = json.dumps({
                "messages": [{
                    "role": "user",
                    "content": [
                        {"image": {"format": "png", "source": {"bytes": img_b64}}},
                        {"text": prompt_text},
                    ],
                }],
                "inferenceConfig": {"max_new_tokens": 512},
            })
        else:
            # Claude format: image block uses {"type": "image", "source": {"type": "base64", ...}}
            body = json.dumps({
                "anthropic_version": "bedrock-2023-05-31",
                "max_tokens": 512,
                "messages": [{
                    "role": "user",
                    "content": [
                        {"type": "image", "source": {"type": "base64", "media_type": "image/png", "data": img_b64}},
                        {"type": "text", "text": prompt_text},
                    ],
                }],
            })

        try:
            # Call Bedrock — this is an HTTP request to AWS
            response = self._bedrock.invoke_model(
                modelId=self.bedrock_model_id,
                body=body,
                contentType="application/json",
                accept="application/json",
            )
            result = json.loads(response["body"].read())

            # Parse the response — structure differs between Nova and Claude
            if is_nova:
                return result["output"]["message"]["content"][0]["text"].strip()
            return result["content"][0]["text"].strip()
        except Exception as exc:
            # Captioning is optional — if it fails, return a safe fallback
            logger.warning("Bedrock captioning failed: %s", exc)
            return "Chart/figure detected (captioning unavailable)."

    def extract_charts(
        self,
        images: list,           # list of EmbeddedImage objects from pdf_parser
        generate_captions: bool = True,
        max_charts: int = 5,    # limit Bedrock calls — each one costs time + money
    ) -> list[ChartNode]:
        """Full pipeline: detect charts with CLIP, then caption them with Bedrock.

        Step 1 — CLIP detection (local, fast, all images processed):
          For each image, call is_chart() to get a chart probability score.
          Keep only images that score above the threshold.

        Step 2 — Sort by confidence, keep top max_charts:
          We cap at 5 charts by default to avoid too many Bedrock calls
          (each call = ~1 second and costs API credits).

        Step 3 — Caption in parallel with ThreadPoolExecutor:
          Multiple Bedrock calls run simultaneously instead of one at a time.
          Like running multiple UiPath robots in parallel.

        Returns a list of ChartNode objects (image + caption + metadata).
        """
        from concurrent.futures import ThreadPoolExecutor, as_completed

        # Step 1: Run CLIP on every image — this is fast and local
        detected_imgs = []
        for emb_img in images:
            pil = emb_img.image
            detected, score, top_label = self.is_chart(pil)
            if detected:
                logger.info("Chart p%d score=%.3f type=%s", emb_img.page_number, score, top_label)
                detected_imgs.append((emb_img, score, top_label))

        # Step 2: Sort by CLIP score (highest first), keep only top max_charts
        detected_imgs.sort(key=lambda x: x[1], reverse=True)
        detected_imgs = detected_imgs[:max_charts]
        logger.info("Captioning %d/%d detected charts", len(detected_imgs), len(images))

        # Step 3: Caption each chart — run in parallel to save time
        def _caption_one(item):
            """Worker function for one chart — called in parallel."""
            emb_img, score, top_label = item
            caption = ""
            if generate_captions:
                # Call Bedrock to get a detailed description of this chart
                caption = self.caption_chart(emb_img.image, source_context=emb_img.source)
            return ChartNode(
                image_bytes=emb_img.to_bytes("PNG"),
                caption=caption,
                chart_type=top_label,
                clip_score=score,
                page_number=emb_img.page_number,
                image_index=emb_img.image_index,
                source=emb_img.source,
                width=emb_img.image.width,
                height=emb_img.image.height,
            )

        chart_nodes: list[ChartNode] = []
        if detected_imgs:
            # Run up to 5 Bedrock caption calls in parallel
            with ThreadPoolExecutor(max_workers=min(5, len(detected_imgs))) as pool:
                futures = [pool.submit(_caption_one, item) for item in detected_imgs]
                for f in as_completed(futures):
                    chart_nodes.append(f.result())

        return chart_nodes

    # ── Private Helpers ───────────────────────────────────────────────────────

    def _encode_labels(self) -> torch.Tensor:
        """Pre-compute normalised CLIP text features for all candidate labels.

        CLIP works by comparing image features to text features.
        We compute the text features for all label strings ONCE at startup
        (they never change) so we don't repeat this work for every image.

        The features are L2-normalised (divided by their magnitude) so that
        similarity = dot product, which is fast to compute.
        """
        # Tokenise all label strings (convert words to token IDs)
        tokens = self._tokenizer(_CHART_LABELS).to(self.device)
        with torch.no_grad():  # no_grad = don't track gradients (faster, less memory)
            text_feats = self._model.encode_text(tokens)
            # L2 normalise: divide each vector by its own magnitude
            text_feats = text_feats / text_feats.norm(dim=-1, keepdim=True)
        return text_feats

    def _clip_classify(self, image: Image.Image) -> tuple[torch.Tensor, str]:
        """Run CLIP on one image and return probability scores + top label.

        Steps:
          1. Preprocess the image (resize, normalise pixel values)
          2. Encode the image to a feature vector
          3. Compute dot product similarity against all label text features
          4. Apply softmax to convert similarity scores to probabilities
          5. Return all probabilities + the label with the highest probability

        The 100.0 scaling factor is CLIP's standard logit scale.
        """
        # Preprocess: resize to CLIP's expected input size, normalise pixels
        img_tensor = self._preprocess(image).unsqueeze(0).to(self.device)  # add batch dimension
        with torch.no_grad():
            # Encode image to a feature vector
            img_feats = self._model.encode_image(img_tensor)
            # L2 normalise
            img_feats = img_feats / img_feats.norm(dim=-1, keepdim=True)
            # Compute similarity: image_features @ text_features^T → shape [1, num_labels]
            # Scale by 100.0 (CLIP's standard temperature), then softmax → probabilities
            logits = (100.0 * img_feats @ self._text_features.T).softmax(dim=-1)
        probs = logits.squeeze(0).cpu()  # remove batch dimension, move to CPU
        top_idx = probs.argmax().item()  # index of the label with highest probability
        return probs, _CHART_LABELS[top_idx]


# ── Utility Functions ─────────────────────────────────────────────────────────

def _image_to_base64(image: Image.Image, fmt: str = "PNG") -> str:
    """Convert a PIL Image to a base64-encoded string.

    Base64 encoding converts binary bytes to ASCII text.
    This is needed to embed images inside JSON payloads sent to Bedrock.

    Like encoding a file as a UiPath Base64String for HTTP requests.
    """
    buf = io.BytesIO()
    image.save(buf, format=fmt)  # write image bytes to an in-memory buffer
    return base64.b64encode(buf.getvalue()).decode("utf-8")  # encode to base64 string
